// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// make_sequence_altrep
SEXP make_sequence_altrep(size_t n, size_t start, size_t step);
RcppExport SEXP _TravelExample_make_sequence_altrep(SEXP nSEXP, SEXP startSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< size_t >::type start(startSEXP);
    Rcpp::traits::input_parameter< size_t >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(make_sequence_altrep(n, start, step));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TravelExample_make_sequence_altrep", (DL_FUNC) &_TravelExample_make_sequence_altrep, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TravelExample(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
