# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_sequence_altrep <- function(n, start, step) {
    .Call(`_TravelExample_make_sequence_altrep`, n, start, step)
}

